[network]
name = "simnet"
node_rpc_address = "http://localhost:20443"
stacks_node_rpc_address = "http://localhost:20443"
bitcoin_node_rpc_address = "http://localhost:18443"
bitcoin_node_rpc_port = 18443
bitcoin_node_rpc_user = "devnet"
bitcoin_node_rpc_pass = "devnet"
use_docker_gateway_as_host = false

[accounts.deployer]
mnemonic = "wink document leader devote author belt such doll suffer inch vocal radio vicious social rent history ivory upgrade skirt purpose square identify place salute"
balance = 100_000_000_000
is_mainnet = false
